### ISSUE TITLE
App Graphics for Sandstorm

### ISSUE THREAD

**Issue by neynah** [jparyani/laverna#1]
@jparyani 

These are the only ones I could find (which I'm OK with). But let me know if you know of others.

![laverna-preview1](https://cloud.githubusercontent.com/assets/855341/9266019/6645f964-41f0-11e5-8856-d111ad816198.png)

**Comment by jparyani** [comment]
LGTM

**Comment by jparyani** [comment]
Fixed by ebf86fd9a0791e51acebaccfe44de8fb0721f309
