### ISSUE TITLE
App does not render properly in Sandstorm Oasis

### ISSUE THREAD

**Issue by liquidsunshine** [jparyani/laverna#3]
![laverna-screenshot](https://cloud.githubusercontent.com/assets/1158592/9706762/411017ac-54be-11e5-8fba-e2dd67664e8c.png)

App's appearance seems wrong.  Notice the border artifact in the background behind the document title box and the repetition of the icons on the editing menu above the title box.

For reference, this happens on Firefox 40.0.3 on Windows 10 and Linux (Fedora 22 with Cinnamon).  Haven't tested it on other browsers or operating systems.

Is there anything else I can provide to help track this down?

**Comment by jparyani** [comment]
Thanks for reporting! This issue doesn't show up in Chrome, so I never noticed during development.

Update should be up on the App Market within the next hour.

**Comment by liquidsunshine** [comment]
Fantastic.  Thanks!
