### ISSUE TITLE
Changes made by non-owner appear to be saved but aren't

### ISSUE THREAD

**Issue by kentonv** [jparyani/laverna#4]
If I share a Laverna grain with an anonymous user and attempt to make changes as that anonymous user, the changes are not saved.

What makes this really bad, though, is that the changes _appear_ to be saved, because they are saved in localStorage, and its only the syncing localStorage to the server that fails. There is no feedback that this sync has failed. So I only notice when I refresh the grain.

I think the first priority here is to make sure there's some sort of feedback if the sync fails. Actually supporting sharing is secondary.

**Comment by jparyani** [comment]
Fixed in https://github.com/jparyani/laverna-sandstorm/commit/8edba2a0206f4cde19487480dc8043459a2e0316
