### ISSUE TITLE
Unable to create new notes in Laverna if I'm renaming the grain during spin-up

### ISSUE THREAD

**Issue by jadeqwang** [jparyani/laverna#5]
I encountered a problem where I'm unable to create new Laverna notes after this sequence. Steps to repro:
1. Create a new Laverna grain
2. While it's still spinning up, open up dialog to rename the grain.
3. Take an extra few seconds to think about what you're renaming the grain. Hit ok.
4. Attempt to start a new note.

Screen recording: https://youtu.be/4YnHDhY8H60

This was fixed by restarting the grain.

**Comment by paulproteus** [comment]
A user reports that they can reproduce this problem without renaming the grain. They are based in Britain. This suggests to me that renaming the grain is a way to simulate JS code execution or file downloading taking a long time, and that there is an underlying issue.

@jparyani if you need help repro-ing, I can now do that, so let me know.

**Comment by paulproteus** [comment]
@jparyani : The symptoms are that the left nav loads, but there are zero notes in it, and that users find this surprising (and perhaps fear that the system deleted all their data).

As I recall, I was able to reproduce it by fiddling with Chromium's ability to throttle its own network bandwidth usage, within the "Network" area of Developer Tools.

**Comment by jparyani** [comment]
See #5 for a related problem. Unfortunately, it's much trickier to track down.
