### ISSUE TITLE
Cannot save language and a few more issues

### ISSUE THREAD

**Issue by ovizii** [jparyani/laverna#7]
- It always reverts to Italiano.
- the full-screen button does nothing
- what is the purpose of the word count info button?
- I see a few JS issues in my console, see screenshot: http://screencast.com/t/1RbRGi6N

**Comment by scrumit** [comment]
Coo, what a lot of tabs you have open in that screen shot. My experience with browsers is that after about 4 or 5 tabs it starts to chug a bit and can take a while to get enough space allocated to load all the data of the page.

I've just tested my oasis.sandstorm.io page loading on Chrome (with only four tabs open) using [uptrends](https://www.uptrends.com/tools/website-speed-test) and I get this picture.

As you'll see the browser is waiting on the CDN for 4.9 seconds. Thankfully there's parallel requests, but the page still takes over 3.25 seconds to load. With lots of tabs open there will be more delays.

The sandstorm page loads 789kB of data. Luckily the Meteor JS files and some graphics are cached. Why isn't the oasis-landing.svg cached (it's being reloaded, possibly from a redirect)?  And quite a lot of the other graphics cause a wait before the cached version is used.

Not a surprise that sometimes loads return a 404. I've seen a 404 tonight on restarting. 

GET https://243c1d76b9cb33fcf57eed7366cc5a72.oasis.sandstorm.io/locales/en-US/translation.json 404 (Not Found)

That will explain why language and other I18N settings go AWOL.

![slowload20170801](https://user-images.githubusercontent.com/2226180/28846911-270ffece-7705-11e7-9def-089f986fc4be.png)

**Comment by ovizii** [comment]
So basically you're saying that the file wasn't found: 

> GET https://243c1d76b9cb33fcf57eed7366cc5a72.oasis.sandstorm.io/locales/en-US/translation.json 404 (Not Found)

Hm, I haven't touched laverna in 2 years since posting this thread  so I just checked and it seems the language is bein saved now.
